spring.application.name=backend

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/elibrary_db
spring.datasource.username=root
spring.datasource.password=NewPassword123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/elibrary?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# file upload size (pdf/epub)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
