server:
  port: 8080
  servlet:
<<<<<<< HEAD
    context-path: /api
=======
<<<<<<< HEAD
    context-path: /api
=======
<<<<<<< HEAD
    context-path: /api
=======
<<<<<<< HEAD
    context-path: /api
=======
    context-path: /
>>>>>>> 214ea6c94b151641970906ae80d8582b1f1a2db5
>>>>>>> 90e533a64b037985637d2a52a5bf42cda436d520
>>>>>>> 7d6a5d204ea17806ab69918b293c59a83a16ffc5
>>>>>>> 8b633b4794f990139a187f791f79171778bb2c11

spring:
  application:
    name: elibrary-backend
    
  datasource:
    url: jdbc:mysql://localhost:3306/elibrary_db
    username: root
    password: "Bharana@2004"
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
=======
<<<<<<< HEAD
      ddl-auto: update
=======
<<<<<<< HEAD
      ddl-auto: update
=======
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: validate
>>>>>>> 214ea6c94b151641970906ae80d8582b1f1a2db5
>>>>>>> 90e533a64b037985637d2a52a5bf42cda436d520
>>>>>>> 7d6a5d204ea17806ab69918b293c59a83a16ffc5
>>>>>>> 8b633b4794f990139a187f791f79171778bb2c11
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  security:
    jwt:
      secret: your-secret-key-change-this-in-production
      expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.elibrary: DEBUG
